      - name: Show app.txt
        run: |
          echo "---- app.txt ----"
          cat app.txt

      - name: Check required line exists
        run: |
          grep -q "CI/CD starts here" app.txt
          echo "Required line found âœ…"

